"""Pass-2 rebalance audit (path-authoritative).

For each thin (1–4 Qs) or empty (0 Qs) proposed pattern, find practice
questions that could honestly be recruited there:

  - **Orphans** — questions in no live path, whose tag-routing suggests
    the thin pattern. Bringing them into the thin pattern's path (or a
    new path for it) is a no-cost gain.
  - **Divergent path members** — questions currently in some other live
    path, but whose tags suggest the thin pattern. Moving them is a real
    reassignment decision; the move is honest only if the question's
    primary objective genuinely belongs in the thin pattern.

Output: appends a "Pass 2 rebalance" section to pattern-coverage-audit.md.

This is a routing-refinement tool, not auto-reassignment. No JSON or
registry changes happen here.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "backend"))
sys.path.insert(0, str(REPO / "scripts"))

from concept_families import resolve_to_family
from audit_pattern_coverage import (
    TRACK_DIRS, PROPOSED_PATTERNS, ROUTING,
    walk_track, classify_pattern, _load_live_paths_by_track,
)


def find_recruitable(track: str, per_question, buckets, orphans, divergences) -> dict[str, dict]:
    """For each thin/empty pattern in this track, return:
        {pattern: {"orphans": [...], "divergents": [...]}}

    Each entry is a per-question record from the audit walk.
    """
    pats = PROPOSED_PATTERNS.get(track, {})
    routes = ROUTING.get(track, {})

    # Reverse map: pattern → set of families that route to it
    pattern_to_families: dict[str, set[str]] = defaultdict(set)
    for fam, pat in routes.items():
        if pat is not None:
            pattern_to_families[pat].add(fam)

    thin_or_empty = [
        p for p in pats
        if classify_pattern(buckets.get(p, [])) in ("THIN", "EMPTY")
    ]

    recruitable: dict[str, dict] = {
        p: {"orphans": [], "divergents": []} for p in thin_or_empty
    }

    # Orphan candidates: tag suggests the thin pattern
    for r in orphans:
        if r["tag_pattern"] in thin_or_empty:
            recruitable[r["tag_pattern"]]["orphans"].append(r)

    # Divergent candidates: in some other path but tags suggest thin pattern
    for r in divergences:
        if r["tag_pattern"] in thin_or_empty:
            recruitable[r["tag_pattern"]]["divergents"].append(r)

    # Sort each pattern's candidates by easy→medium→hard for review order
    diff_order = {"easy": 0, "medium": 1, "hard": 2}
    for thin in recruitable:
        recruitable[thin]["orphans"].sort(key=lambda r: (diff_order.get(r["difficulty"], 9), r["qid"]))
        recruitable[thin]["divergents"].sort(key=lambda r: (diff_order.get(r["difficulty"], 9), r["qid"]))

    return recruitable


def render_rebalance_markdown(rebalance_by_track: dict, pattern_current_counts: dict) -> str:
    lines: list[str] = []
    lines.append("---")
    lines.append("## Pass 2: Rebalance recommendations")
    lines.append("")
    lines.append("**Generated by:** `scripts/audit_pattern_rebalance.py`.")
    lines.append("")
    lines.append("For each **thin** (1–4 Qs) or **empty** (0 Qs) proposed pattern, this section")
    lines.append("lists practice questions that could honestly be recruited into the pattern.")
    lines.append("Two recruitment sources:")
    lines.append("")
    lines.append("- **Orphans** — questions in no live path whose tag-routing suggests the")
    lines.append("  thin pattern. These are zero-cost gains: either add them to an existing")
    lines.append("  path for the thin pattern, or use them as the seed for a new path.")
    lines.append("- **Divergent path members** — questions currently in some other live path,")
    lines.append("  whose tags suggest the thin pattern. Moving them is a real reassignment")
    lines.append("  decision; the move is honest only if the question's *primary objective*")
    lines.append("  genuinely belongs in the thin pattern.")
    lines.append("")
    lines.append("**How to use this section:**")
    lines.append("")
    lines.append("1. Review the orphan list first — these are easy wins.")
    lines.append("2. For divergents, read each question and decide whether the move is honest")
    lines.append("   (does the question's primary objective match the thin pattern, or is the")
    lines.append("   tag-overlap incidental?).")
    lines.append("3. If many honest moves exist, the thin pattern can become healthy with")
    lines.append("   zero new authoring.")
    lines.append("4. If no candidates honestly fit, the thin pattern genuinely needs new")
    lines.append("   content authoring (the `needs_content` flag stays).")
    lines.append("")
    lines.append("**This is a routing-refinement tool, not auto-reassignment.**")
    lines.append("No JSON or registry changes happen by running it.")
    lines.append("")

    # Headline impact: per-pattern current count + max-potential if all candidates recruited
    lines.append("### Potential rebalance impact (upper bound)")
    lines.append("")
    lines.append("If *every* recruitable candidate (orphans + divergents) were honestly")
    lines.append("recruited (upper bound — reality is lower), how each thin/empty pattern's")
    lines.append("count would change. Divergents require more author scrutiny than orphans.")
    lines.append("")
    lines.append("| Track | Pattern | Current | + Orphans | + Divergents | Max potential | Becomes |")
    lines.append("|---|---|---:|---:|---:|---:|---|")
    for track in TRACK_DIRS:
        rec = rebalance_by_track.get(track, {})
        if not rec:
            continue
        track_counts = pattern_current_counts.get(track, {})
        for thin_pattern in sorted(rec.keys()):
            entries = rec[thin_pattern]
            n_orph = len(entries["orphans"])
            n_div = len(entries["divergents"])
            if n_orph == 0 and n_div == 0:
                continue
            current = track_counts.get(thin_pattern, 0)
            max_pot = current + n_orph + n_div
            if max_pot >= 5:
                becomes = "✅ healthy potential"
            elif max_pot > 0:
                becomes = "🟡 still thin"
            else:
                becomes = "🔴 still empty"
            lines.append(
                f"| {track} | `{thin_pattern}` | {current} | {n_orph} | {n_div} | {max_pot} | {becomes} |"
            )
    lines.append("")

    # Per-pattern detail sections
    for track in TRACK_DIRS:
        rec = rebalance_by_track.get(track, {})
        if not rec:
            continue
        any_content = any(
            entries["orphans"] or entries["divergents"]
            for entries in rec.values()
        )
        if not any_content:
            continue
        lines.append(f"### {track}")
        lines.append("")
        for thin_pattern in sorted(rec.keys()):
            entries = rec[thin_pattern]
            if not entries["orphans"] and not entries["divergents"]:
                continue
            label = PROPOSED_PATTERNS.get(track, {}).get(thin_pattern, thin_pattern)
            lines.append(f"#### `{thin_pattern}` — {label}")
            lines.append("")
            n_orph = len(entries["orphans"])
            n_div = len(entries["divergents"])
            lines.append(f"_{n_orph} orphan candidate{'s' if n_orph != 1 else ''} · "
                         f"{n_div} divergent candidate{'s' if n_div != 1 else ''}_")
            lines.append("")

            if entries["orphans"]:
                lines.append("**Orphans** (in no live path; zero-cost recruitment):")
                lines.append("")
                lines.append("| QID | Diff | Title | Concepts |")
                lines.append("|---|---|---|---|")
                for r in entries["orphans"][:30]:
                    title = r["title"].replace("|", "\\|")
                    concepts_repr = ", ".join(f"`{c}`" for c in r["concepts"])
                    lines.append(f"| {r['qid']} | {r['difficulty']} | {title} | {concepts_repr} |")
                if len(entries["orphans"]) > 30:
                    lines.append(f"| _… {len(entries['orphans'])-30} more not shown_ | | | |")
                lines.append("")

            if entries["divergents"]:
                lines.append("**Divergents** (in another live path; review per question):")
                lines.append("")
                lines.append("| QID | Diff | Currently in | Attributed pattern | Title |")
                lines.append("|---|---|---|---|---|")
                for r in entries["divergents"][:30]:
                    title = r["title"].replace("|", "\\|")
                    lines.append(
                        f"| {r['qid']} | {r['difficulty']} | `{r['live_path']}` | "
                        f"`{r['attributed_pattern']}` | {title} |"
                    )
                if len(entries["divergents"]) > 30:
                    lines.append(f"| _… {len(entries['divergents'])-30} more not shown_ | | | | |")
                lines.append("")
        lines.append("")

    return "\n".join(lines)


def main():
    live_paths_by_track = _load_live_paths_by_track()
    rebalance_by_track = {}
    pattern_current_counts: dict[str, dict[str, int]] = {}

    for track, content_dir in TRACK_DIRS.items():
        per_q, buckets, _, orphans, divergences = walk_track(
            track, content_dir, live_paths=live_paths_by_track.get(track, [])
        )
        recruitable = find_recruitable(track, per_q, buckets, orphans, divergences)
        rebalance_by_track[track] = recruitable
        pattern_current_counts[track] = {
            slug: len(buckets.get(slug, []))
            for slug in PROPOSED_PATTERNS.get(track, {})
        }

    rebalance_md = render_rebalance_markdown(rebalance_by_track, pattern_current_counts)

    audit_path = REPO / "docs" / "phases" / "pattern-coverage-audit.md"
    existing = audit_path.read_text()
    marker = "---\n## Pass 2: Rebalance recommendations"
    if marker in existing:
        existing = existing.split(marker)[0].rstrip() + "\n"
    audit_path.write_text(existing + "\n" + rebalance_md)
    print(f"Appended Pass 2 section to {audit_path}")

    print()
    print("Rebalance headline (per thin pattern: orphans + divergents):")
    for track, rec in rebalance_by_track.items():
        any_content = any(e["orphans"] or e["divergents"] for e in rec.values())
        if not any_content:
            continue
        print(f"\n  {track}:")
        for thin in sorted(rec.keys()):
            entries = rec[thin]
            n_o = len(entries["orphans"])
            n_d = len(entries["divergents"])
            if n_o or n_d:
                print(f"    {thin:>40}  orph={n_o:>2}  div={n_d:>2}")


if __name__ == "__main__":
    main()
